entities:
  prompt: src/prompts/entities-only.txt
  schema: src/schemas/entities.json
  function_name: extract_clean_tech_entities
  top_key: nodes
  model_key: nodes

capacities:
  prompt: src/prompts/capacities.txt
  schema: src/schemas/capacities.json
  function_name: extract_characteristics
  top_key: node_characteristics
  model_key: capacities
  id_key: capacity_ID  
  type_match: capacity

investments:
  prompt: src/prompts/investments.txt
  schema: src/schemas/investments.json
  function_name: extract_characteristics
  top_key: node_characteristics
  model_key: investments
  id_key: investment_ID 
  type_match: investment

ownership:
  prompt: src/prompts/ownership.txt
  schema: src/schemas/ownership.json
  function_name: extract_clean_tech_relationships
  top_key: relationships
  model_key: ownership

technological:
  prompt: src/prompts/technological.txt
  schema: src/schemas/technological.json
  function_name: extract_clean_tech_relationships
  top_key: relationships
  model_key: technological

financial_origin:
  prompt: src/prompts/financial_origin.txt
  schema: src/schemas/financial_origin.json
  function_name: extract_clean_tech_relationships
  top_key: relationships
  model_key: financial_origin

financial_technological:
  prompt: src/prompts/financial_technological.txt
  schema: src/schemas/financial_technological.json
  function_name: extract_clean_tech_relationships
  top_key: relationships
  model_key: financial_technological