import re

BOILER_STRINGS = {
    "Your email address will not be published.Required fields are marked*",
    "Name *",
    "E-Mail *",
    "I agree with thePrivacy policy",
    "© 2025 electrive.com",
    "electrive has been following the development of electric mobility with journalistic passion and expertise since 2013. As the industry's leading trade media, we offer comprehensive coverage of the highest quality — as a central platform for the rapid development of this technology. With news, background information, driving reports, interviews, videos and advertising messages.",
    "The gold standard of business intelligence.",
    "Find out more",
    "Give your business an edge with our leading industry insights.",
    "Future Power Technology : Power Technology Focus (monthly)",
    "Thematic Take (monthly)",
    "Visit ourPrivacy Policyfor more information about our services, how we may use, process and share your personal data, including information on your rights in respect of your personal data and how you can unsubscribe from future marketing communications. Our services are intended for corporate subscribers and you warrant that the email address submitted is your corporate email address.",
    "View all newslettersfrom across the GlobalData Media network.",
    "Power industry news, data and in-depth articles on the global trends driving power generation, renewables and innovation",
    "Powered by",
    "© Verdict Media Limited 2025",
    "This article is reproduced at argusmedia.com",
    "As our energy demands grow greater, renewable energy is key to the future of our planet. Harnessing the power of wind is essential. At Aggreko, we have over 60 years’ experience and an in-depth understanding of the power and temperature control needs of wind farms. We have a dedicated Wind Energy Team whose innovative strategies […]",
    "Daily news and in-depth stories in your inbox",
    "Share this article",
    "Follow us",
    "This content is protected by copyright and may not be reused. If you want to cooperate with us and would like to reuse some of our content, please contact:editors@pv-magazine.com.",
    "Please be mindful of ourcommunity standards.",
    "Your email address will not be published.Required fields are marked*",
    "Comment*",
    "Name*",
    "Email*",
    "Website",
    "Save my name, email, and website in this browser for the next time I comment.",
    "By submitting this form you agree to pv magazine using your data for the purposes of publishing your comment.",
    "Your personal data will only be disclosed or otherwise transmitted to third parties for the purposes of spam filtering or if this is necessary for technical maintenance of the website. Any other transfer to third parties will not take place unless this is justified on the basis of applicable data protection regulations or if pv magazine is legally obliged to do so.",
    "You may revoke this consent at any time with effect for the future, in which case your personal data will be deleted immediately. Otherwise, your data will be deleted if pv magazine has processed your request or the purpose of data storage is fulfilled.",
    "Further information on data privacy can be found in ourData Protection Policy.",
    "Legal NoticeTerms and ConditionsData Privacy© pv magazine 2025",
    "This website uses cookies to anonymously count visitor numbers.View our privacy policy.×",
    "The cookie settings on this website are set to \"allow cookies\" to give you the best browsing experience possible. If you continue to use this website without changing your cookie settings or you click \"Accept\" below then you are consenting to this.",
    "Close",
    "Δ",
    "More articles from Marian Willuhn",
    "More articles from Uma Gupta",
    "More articles from Brian Publicover",
    "More articles from Rachel Metea",
    "More articles from Vincent Shaw",
    "More articles from Ryan Kennedy",
    "More articles from David Carroll",
    "More articles from Patrick Jowett",
    "More articles from Matthew Lynas",
    "More articles from John Fitzgerald Weaver",
    "Frompv magazine USA",
    "Image: Wikimedia Commons, Wikideas",
    "More articles from Tristan Rayner",
    "To continue reading, please visit ourESS Newswebsite.",
    "Image: Northvolt",
    "Frompv magazine India",
    "More articles from Luis Ini",
    "Image: pv magazine",
    "More articles from Matthew Lynas",
    "By clicking here, you agree to ourTerms and Conditionsand consent to us collection your details for the purposes of your enquiry",
    "Automotive Industry News & Analysis | Market Research - Just Auto",
    "Just Auto : Just Auto Focus (monthly)",
    "Gain the recognition you deserve! TheJust Auto Excellence Awardscelebrate innovation, leadership, and impact. By entering, you showcase your achievements, elevate your industry profile, and position yourself among top leaders driving automotive industry advancements. Don’t miss your chance to stand out—submit your entry today!",
    "Don’t let policy changes catch you off guard. Stay proactive with real-time data and expert analysis.",
    "Renews provides news-focused business intelligence on the renewable energy sector with market-leading coverage of offshore and onshore wind.",
    "Please select the Daily reNEWS.biz newsletters that you would like to receive from the list below. Click on the sign-up button and fill in your details",
    "Battery-News © 2025 |Imprint|Privacy Policy",
    "Ich habe dieDatenschutzerklärunggelesen und stimme ihr zu.",
    "Nachname",
    "Vorname",
    "E-Mail-Adresse",
    "Greg Morris has been editor of Glass International and organiser of the Glassman conferences since 2012, specialising in glass packaging. Prior to this he spent five years working in newspaper journalism.",
    "Greg Morris has been editor of Glass International and organiser of the Glassman conferences since 2012, specialising in glass packaging. Prior to this he spent five years working in newspaper journalism.",
    "© All rights reserved.",
    "Just Auto : Just Auto Focus (monthly)",
    "Automotive Industry News & Analysis | Market Research - Just Auto",
    "By clicking here, you agree to ourTerms and Conditionsand consent to us collection your details for the purposes of your enquiry",
    "Gain the recognition you deserve! TheJust Auto Excellence Awardscelebrate innovation, leadership, and impact. By entering, you showcase your achievements, elevate your industry profile, and position yourself among top leaders driving automotive industry advancements. Don’t miss your chance to stand out—submit your entry today!",
    "Don’t let policy changes catch you off guard. Stay proactive with real-time data and expert analysis.",
    "Combine business intelligence and editorial excellence to reach engaged professionals across 36 leading media platforms.",
    "Follow offshoreWIND.biz on:",
    "Daily news and in-depth stories in your inbox",
    "+ + Kindly see our updates below + +",
    "Stay up to date with the latest news, trends and innovations that are driving the global automotive industry with the Reuters Auto.",
    "electrive has been reporting on the development of electric mobility with journalistic depth and industry expertise since 2011 and has been available in English since 2013. As the industry's leading voice on e-mobility, electrive provides high-quality coverage and in-depth reporting on the rapid evolution of e-mobility, including news, background features, interviews, videos and industry communications.",
    "newswire.ca",
    "© 2026 electrive.com",
    "Please be mindful of ourcommunity standards.",
    "This content is protected by copyright and may not be reused. If you want to cooperate with us and would like to reuse some of our content, please contact:editors@pv-magazine.com.",
    "Image source: Siemens Energy",
    "Source: Siemens Energy",
    "Subscribe to Magazine!",
    "Subscribe",
    "Source : Link",
    "Source: Auto Bild 5/2016, print edition",
    "(Debreceni Nap)",
    "np-coburg.de(in German)",
    "autonews.com,heise.de(in German)",
    "automobilwoche.de(in German)",
    "wsj.com,autonews.com",
    "motoring.com.au,worldcarfans.com,insideevs.com",
    "gummibereifung.de(Pirelli, in German),teslarati.com(Model X tires specs)",
    "electriccarsreport.com,audi-mediacenter.com",
    "motoring.com.auviagreencarreports.com",
    "autoblog.com,electrek.co,insideevs.com",
    "Every workday,“electrive.com today”delivers the latest electric-mobility news from around the world right to your inbox – short, to the point and free of charge. We cover global stories but also keep a focus on relevant news from the German electric car industry! Anyone, that would like to receive a free subscription, just needs to email us at subscribe@electrive.com or visitwww.electrive.com",
    "electriccarsreport.com,fiaformulae.com,youtube.com(race highlights)",
}