INVESTMENT_PHASE_FIELDS = {
    "country": str,
    "location": str,
    "company": str,
    "tech": str,
    "component": str,
    "phase": str,
    "investment_value": str,
    "capacity": str,
    "status": str,
    "dt_announce": str,
    "dt_actual": str,
    "dt_operational": str,
    "dt_cancel": str,
    "jobs": str,
    "checked": bool,
    "reject-phase": bool,
    "finetune": bool,
    "share-investment": bool,
    "note": str
}